# USAGE_FAM_MAPPING dictionary
USAGE_FAM_MAPPING = {
    "AWS Service Catalog": "AWSServiceCatalog",
    "Amazon Simple Queue Service": "AWSQueueService",
    "AWS Glue": "AWSGlue",
    "AWS Data Transfer": "AWSDataTransfer",
    "AWS Secrets Manager": "AWSSecretsManager",
    "AWS Key Management Service": "awskms",
    "Amazon Simple Notification Service": "AmazonSNS",
    "Amazon Simple Storage Service": "AmazonS3",
    "AmazonCloudWatch": "AmazonCloudWatch",
    "AWS Migration Hub Refactor Spaces": "AWSMigrationHubRefactorSpaces",
    "AWS Lambda": "AWSLambda",
    "Amazon Elastic Compute Cloud": "AmazonEC2",
    "AWS CloudTrail": "AWSCloudTrail",
    "Amazon DynamoDB": "AmazonDynamoDB",
    "Amazon Relational Database Service": "AmazonRDS",
    "Amazon API Gateway": "AmazonApiGateway",
    "Amazon Elastic Container Registry Public": "AmazonECRPublic",
    "Amazon EC2 Container Registry (ECR)": "AmazonECR",
    "Amazon Virtual Private Cloud": "AmazonVPC",
    "Amazon Elastic Container Service": "AmazonECS",
    "Elastic Load Balancing": "AWSELB",
    "Amazon S3 Glacier Deep Archive": "AmazonS3GlacierDeepArchive",
    "Amazon Elastic File System": "AmazonEFS",
    "Amazon Rekognition": "AmazonRekognition",
    "Amazon Simple Email Service": "AmazonSES",
    "Amazon ElastiCache": "AmazonElastiCache",
    "Amazon OpenSearch Service": "AmazonES",
    "AWS DataSync": "AWSDataSync",
    "Amazon CloudFront": "AmazonCloudFront",
    "AWS Cost Explorer": "AWSCostExplorer",
    "AWS X-Ray": "AWSXRay",
    "Amazon Route 53": "AmazonRoute53",
    "Amazon Kinesis": "AmazonKinesis",
    "Amazon Redshift": "AmazonRedshift",
    "AWS Config": "AWSConfig",
    "AWS Elemental MediaLive": "AWSElementalMediaLive",
    "AWS Transfer Family": "AWSTransfer",
    "CloudWatch Events": "AWSEvents",
    "Amazon SimpleDB": "AmazonSimpleDB",
    "Amazon Elastic Container Service for Kubernetes": "AmazonEKS",
    "Amazon Lightsail": "AmazonLightsail",
    "AWS Backup": "AWSBackup",
    "Amazon Cognito": "AmazonCognito",
    "AWS Systems Manager": "AWSSystemsManager",
    "Amazon Elastic Compute Cloud - Compute": "AmazonEC2",
    "Tax": "AWSBilling",
    "Meta Llama 2 Chat 70B (Amazon Bedrock Edition)": "AmazonBedrockLlama70B",
    "Amazon Glacier": "AmazonS3GlacierDeepArchive",
    "AWS CloudFormation": "AWSCloudFormation",
    "Amazon Location Service": "AmazonLocation",
    "Amazon Managed Service for Prometheus": "AWSPrometheus",
    "Amazon Registrar": "AmazonRegistrar",
    "AWS WAF": "AWSWAF",
    "AWS Step Functions": "AWSStepFunctions",
    "Amazon SageMaker": "AmazonSageMaker",
    "Amazon Simple Workflow Service": "AmazonSWF",
    "Amazon Bedrock": "AmazonBedrock",
    "Amazon Interactive Video Service": "AmazonIVS",
    "Amazon MQ": "AmazonMQ",
    "Amazon Elastic Load Balancing": "AWSELB",
    "AWS CloudShell": "AWSCloudShell",
}

#gcp
PROJECT_NAME_MAPPING = {
    "Android-Store": "Android-Store",
    "Android-Store-stage": "Android-Store-stage",
    "AY Corporate AI": "AY Corporate AI",
    "AY Customer Data P1": "AY Customer Data P1",
    "AY Customer Data TrafficJunky": "AY Customer Data TrafficJunky",
    "AY Devops Internal": "AY Devops Internal",
    "AY DevOps Sentry": "AY DevOps Sentry",
    "AY GA4 Data": "AY GA4 Data",
    "ay-infrasec-prismacloud": "ay-infrasec-prismacloud",
    "ay-infrasec-terraform": "ay-infrasec-terraform",
    "ay-infrasec-tfdemo2": "ay-infrasec-tfdemo2",
    "Aylo Billing": "Aylo Billing",
    "Aylo Billing USD": "Aylo Billing USD",
    "Aylo Customer Data Nutaku": "Aylo Customer Data Nutaku",
    "aylo-devops-ai": "aylo-devops-ai",
    "AY Log Archive": "AY Log Archive",
    "Aylo-GCP-Cloud-IDS": "Aylo-GCP-Cloud-IDS",
    "Aylo Legal Freesites": "Aylo Legal Freesites",
    "Aylo Looker": "Aylo Looker",
    "Aylo Probiller SAAS MGPG Prod": "Aylo Probiller SAAS MGPG Prod",
    "Aylo Probiller SaaS Stage": "Aylo Probiller SaaS Stage",
    "AY Nutaku Social TPA": "AY Nutaku Social TPA",
    "AY P1 Social Bangbros": "AY P1 Social Bangbros",
    "AY P1 Social Brazzers": "AY P1 Social Brazzers",
    "AY P1 Social DigitalPlayground": "AY P1 Social DigitalPlayground",
    "ay-projectfactory-demo1": "ay-projectfactory-demo1",
    "ay-projectfactory-tf-test4": "ay-projectfactory-tf-test4",
    "ay-reality-integrations": "ay-reality-integrations",
    "AY Redirector": "AY Redirector",
    "AY TJ CMS UAT": "AY TJ CMS UAT",
    "AY UVIU": "AY UVIU",
    "AY Web Performance": "AY Web Performance",
    "Chatbot-Lite": "Chatbot-Lite",
    "Databricks": "Databricks",
    "forsetisecurity": "forsetisecurity",
    "Gemini API": "Gemini API",
    "ManageMyData-EU-Email-Form": "ManageMyData-EU-Email-Form",
    "mg-adtool": "mg-adtool",
    "MG Adtool": "MG Adtool",
    "MG Ageguard Dev": "MG Ageguard Dev",
    "MG Ageguard Prod": "MG Ageguard Prod",
    "MG AppSec": "MG AppSec",
    "MG Atlas": "MG Atlas",
    "mg-bes c3549": "mg-bes c3549",
    "MG Bot": "MG Bot",
    "MG Broadcaster Dev": "MG Broadcaster Dev",
    "MG Central Logs and Billing": "MG Central Logs and Billing",
    "MG Cloudteam Test": "MG Cloudteam Test",
    "MG Corporate": "MG Corporate",
    "MG Corporate ECP": "MG Corporate ECP",
    "MG Corporate Home": "MG Corporate Home",
    "MG COSE MTL Dev": "MG COSE MTL Dev",
    "MG COSE RO Dev": "MG COSE RO Dev",
    "MG Customer Data MDH": "MG Customer Data MDH",
    "MG Customer Data Platform": "MG Customer Data Platform",
    "MG Databricks": "MG Databricks",
    "MG Data Elastic": "MG Data Elastic",
    "MG Datahub": "MG Datahub",
    "MG DataWarehouse": "MG DataWarehouse",
    "MG DevOps Certificates": "MG DevOps Certificates",
    "MG DevOps CSAI": "MG DevOps CSAI",
    "MG DevOps Encoding": "MG DevOps Encoding",
    "MG DevOps General": "MG DevOps General",
    "MG DevOps Gitlab": "MG DevOps Gitlab",
    "MG DevOps Monitoring": "MG DevOps Monitoring",
    "MG DevOps Streamkube": "MG DevOps Streamkube",
    "MG DevOps Testing": "MG DevOps Testing",
    "MG-Dialogflow": "MG-Dialogflow",
    "mg-dmp": "mg-dmp",
    "MG DMP Dev": "MG DMP Dev",
    "MG DMP Prod": "MG DMP Prod",
    "MG DMP Stage": "MG DMP Stage",
    "MG Document Review": "MG Document Review",
    "Mg Germany": "Mg Germany",
    "MG Gitlab PCI": "MG Gitlab PCI",
    "MG Keycloak Dev": "MG Keycloak Dev",
    "MG Keycloak Infra Prod": "MG Keycloak Infra Prod",
    "MG Keycloak Nutaku Prod": "MG Keycloak Nutaku Prod",
    "MG Keycloak P1 Preprod": "MG Keycloak P1 Preprod",
    "MG Keycloak P1 Prod": "MG Keycloak P1 Prod",
    "MG Keycloak Preprod": "MG Keycloak Preprod",
    "MG Keycloak Prod": "MG Keycloak Prod",
    "MG MAM": "MG MAM",
    "MG MDH ABVP": "MG MDH ABVP",
    "MG MDH Prod": "MG MDH Prod",
    "MG Mixpanel": "MG Mixpanel",
    "MG MSblog": "MG MSblog",
    "MG Networking": "MG Networking",
    "MG Networking Test1": "MG Networking Test1",
    "MG Networking Test2": "MG Networking Test2",
    "MG P1 Dev": "MG P1 Dev",
    "MG P1 Prod": "MG P1 Prod",
    "MG P1 SecretManager": "MG P1 SecretManager",
    "MG PaloAlto Cortex XDR": "MG PaloAlto Cortex XDR",
    "MG PASE Dev": "MG PASE Dev",
    "MG PASE Prod": "MG PASE Prod",
    "MG PCaaS Dev": "MG PCaaS Dev",
    "MG PCaaS-NG": "MG PCaaS-NG",
    "MG PCaaS Prod": "MG PCaaS Prod",
    "MG PoC Dataproc": "MG PoC Dataproc",
    "MG Pornhub": "MG Pornhub",
    "MG Pornhub Net": "MG Pornhub Net",
    "MG Pornhub Org": "MG Pornhub Org",
    "MG Pornhub Premium": "MG Pornhub Premium",
    "MG Probiller Dev": "MG Probiller Dev",
    "MG Probiller Network": "MG Probiller Network",
    "MG Probiller Prod": "MG Probiller Prod",
    "MG Probiller Stage": "MG Probiller Stage",
    "MG Probiller UI Dev": "MG Probiller UI Dev",
    "MG Probiller UI Prod": "MG Probiller UI Prod",
    "MG Probiller UI Stage": "MG Probiller UI Stage",
    "mg-reblaze": "mg-reblaze",
    "MG Safeguard Dev": "MG Safeguard Dev",
    "MG Safeguard Prod": "MG Safeguard Prod",
    "MG Sales Pendo": "MG Sales Pendo",
    "MG SearchLight": "MG SearchLight",
    "MG SearchLight - Parallel": "MG SearchLight - Parallel",
    "MG SearchLight - Staging": "MG SearchLight - Staging",
    "MG Security Defectdojo": "MG Security Defectdojo",
    "MG Security Testing": "MG Security Testing",
    "MG SEO": "MG SEO",
    "MG Services Dev": "MG Services Dev",
    "MG SG Upload": "MG SG Upload",
    "MG Stoplight": "MG Stoplight",
    "MG Surfacing Dev": "MG Surfacing Dev",
    "MG TestPeter": "MG TestPeter",
    "MG Test Sandbox": "MG Test Sandbox",
    "mg-test-terraform1": "mg-test-terraform1",
    "mg-test-terraform2": "mg-test-terraform2",
    "mg-test-terraform3": "mg-test-terraform3",
    "MG TJ Dev": "MG TJ Dev",
    "mg-trafficjunky c3721": "mg-trafficjunky c3721",
    "MG Tubes": "MG Tubes",
    "MG Tubes CSAI Prod": "MG Tubes CSAI Prod",
    "Nutaku Platform": "Nutaku Platform",
    "NutakuPN-prod": "NutakuPN-prod",
    "NutakuWeb-Stage": "NutakuWeb-Stage"
}

GCP_REGIONS = {
    "africa-south1": "africa-south1",
    "asia-east1": "asia-east1",
    "asia-east2": "asia-east2",
    "asia-northeast1": "asia-northeast1",
    "asia-northeast2": "asia-northeast2",
    "asia-northeast3": "asia-northeast3",
    "asia-south1": "asia-south1",
    "asia-south2": "asia-south2",
    "asia-southeast1": "asia-southeast1",
    "asia-southeast2": "asia-southeast2",
    "australia-southeast1": "australia-southeast1",
    "australia-southeast2": "australia-southeast2",
    "europe-central2": "europe-central2",
    "europe-north1": "europe-north1",
    "europe-north2": "europe-north2",
    "europe-southwest1": "europe-southwest1",
    "europe-west1": "europe-west1",
    "europe-west10": "europe-west10",
    "europe-west12": "europe-west12",
    "europe-west2": "europe-west2",
    "europe-west3": "europe-west3",
    "europe-west4": "europe-west4",
    "europe-west6": "europe-west6",
    "europe-west8": "europe-west8",
    "europe-west9": "europe-west9",
    "me-central1": "me-central1",
    "me-central2": "me-central2",
    "me-west1": "me-west1",
    "northamerica-northeast1": "northamerica-northeast1",
    "northamerica-northeast2": "northamerica-northeast2",
    "northamerica-south1": "northamerica-south1",
    "southamerica-east1": "southamerica-east1",
    "southamerica-west1": "southamerica-west1",
    "us-central": "us-central",
    "us-central1": "us-central1",
    "us-central2": "us-central2",
    "us-east1": "us-east1",
    "us-east4": "us-east4",
    "us-east5": "us-east5",
    "us-east7": "us-east7",
    "us-south1": "us-south1",
    "us-west1": "us-west1",
    "us-west2": "us-west2",
    "us-west3": "us-west3",
    "us-west4": "us-west4",
    "us-west8": "us-west8"
}

GCP_COUNTRIES = {
    "AU": "AU",
    "BE": "BE",
    "BR": "BR",
    "CA": "CA",
    "CH": "CH",
    "CL": "CL",
    "DE": "DE",
    "ES": "ES",
    "FI": "FI",
    "FR": "FR",
    "GB": "GB",
    "HK": "HK",
    "ID": "ID",
    "IE": "IE",
    "IL": "IL",
    "IN": "IN",
    "IT": "IT",
    "JP": "JP",
    "KR": "KR",
    "MX": "MX",
    "NL": "NL",
    "PL": "PL",
    "QA": "QA",
    "SA": "SA",
    "SE": "SE",
    "SG": "SG",
    "TW": "TW",
    "US": "US",
    "ZA": "ZA"
}

GCP_SELLERS = {
    "Bitnami": "Bitnami",
    "Clickhouse Inc": "Clickhouse Inc",
    "Databricks, INC.": "Databricks, INC.",
    "Elasticsearch B.V.": "Elasticsearch B.V.",
    "Google": "Google",
    "Google Click to Deploy": "Google Click to Deploy",
    "REBLAZE TECHNOLOGIES LTD": "REBLAZE TECHNOLOGIES LTD"
}

#azure
RESOURCE_MAPPING = {
    "microsoft.aad/domainservices": "microsoft.aad/domainservices",
    "microsoft.appconfiguration/configurationstores": "microsoft.appconfiguration/configurationstores",
    "microsoft.app/containerapps": "microsoft.app/containerapps",
    "microsoft.automation/automationaccounts": "microsoft.automation/automationaccounts",
    "microsoft.azureactivedirectory/b2cdirectories": "microsoft.azureactivedirectory/b2cdirectories",
    "microsoft.botservice/botservices": "microsoft.botservice/botservices",
    "microsoft.cache/redis": "microsoft.cache/redis",
    "microsoft.cdn/profiles": "microsoft.cdn/profiles",
    "microsoft.classicnetwork/ipv4vip": "microsoft.classicnetwork/ipv4vip",
    "microsoft.cognitiveservices/accounts": "microsoft.cognitiveservices/accounts",
    "microsoft.compute/disks": "microsoft.compute/disks",
    "microsoft.compute/galleries": "microsoft.compute/galleries",
    "microsoft.compute/images": "microsoft.compute/images",
    "microsoft.compute/snapshots": "microsoft.compute/snapshots",
    "microsoft.compute/virtualmachines": "microsoft.compute/virtualmachines",
    "microsoft.compute/virtualmachinescalesets": "microsoft.compute/virtualmachinescalesets",
    "microsoft.containerinstance/containergroups": "microsoft.containerinstance/containergroups",
    "microsoft.containerregistry/registries": "microsoft.containerregistry/registries",
    "microsoft.containerservice/managedclusters": "microsoft.containerservice/managedclusters",
    "microsoft.databricks/workspaces": "microsoft.databricks/workspaces",
    "microsoft.datafactory/factories": "microsoft.datafactory/factories",
    "microsoft.datalakeanalytics/accounts": "microsoft.datalakeanalytics/accounts",
    "microsoft.datalakestore/accounts": "microsoft.datalakestore/accounts",
    "microsoft.dbformysql/servers": "microsoft.dbformysql/servers",
    "microsoft.dbforpostgresql/flexibleservers": "microsoft.dbforpostgresql/flexibleservers",
    "microsoft.documentdb/databaseaccounts": "microsoft.documentdb/databaseaccounts",
    "microsoft.eventgrid/domains": "microsoft.eventgrid/domains",
    "microsoft.eventgrid/extensiontopics": "microsoft.eventgrid/extensiontopics",
    "microsoft.eventhub/namespaces": "microsoft.eventhub/namespaces",
    "microsoft.fabric/capacities": "microsoft.fabric/capacities",
    "microsoft.hybridcompute/machines": "microsoft.hybridcompute/machines",
    "microsoft.insights/actiongroups": "microsoft.insights/actiongroups",
    "microsoft.insights/components": "microsoft.insights/components",
    "microsoft.insights/metricalerts": "microsoft.insights/metricalerts",
    "microsoft.insights/scheduledqueryrules": "microsoft.insights/scheduledqueryrules",
    "microsoft.keyvault/vaults": "microsoft.keyvault/vaults",
    "microsoft.kusto/clusters": "microsoft.kusto/clusters",
    "microsoft.logic/workflows": "microsoft.logic/workflows",
    "microsoft.network/applicationgateways": "microsoft.network/applicationgateways",
    "microsoft.network/bastionhosts": "microsoft.network/bastionhosts",
    "microsoft.network/connections": "microsoft.network/connections",
    "microsoft.network/dnsresolvers": "microsoft.network/dnsresolvers",
    "microsoft.network/dnszones": "microsoft.network/dnszones",
    "microsoft.network/loadbalancers": "microsoft.network/loadbalancers",
    "microsoft.network/natgateways": "microsoft.network/natgateways",
    "microsoft.network/networkmanagers": "microsoft.network/networkmanagers",
    "microsoft.network/networkwatchers": "microsoft.network/networkwatchers",
    "microsoft.network/privatednszones": "microsoft.network/privatednszones",
    "microsoft.network/privateendpoints": "microsoft.network/privateendpoints",
    "microsoft.network/publicipaddresses": "microsoft.network/publicipaddresses",
    "microsoft.network/publicipprefixes": "microsoft.network/publicipprefixes",
    "microsoft.network/trafficmanagerprofiles": "microsoft.network/trafficmanagerprofiles",
    "microsoft.network/virtualnetworkgateways": "microsoft.network/virtualnetworkgateways",
    "microsoft.operationalinsights/workspaces": "microsoft.operationalinsights/workspaces",
    "microsoft.powerbidedicated/capacities": "microsoft.powerbidedicated/capacities",
    "microsoft.powerplatform/accounts": "microsoft.powerplatform/accounts",
    "microsoft.purview/accounts": "microsoft.purview/accounts",
    "microsoft.recoveryservices/vaults": "microsoft.recoveryservices/vaults",
    "microsoft.saas/resources": "microsoft.saas/resources",
    "microsoft.search/searchservices": "microsoft.search/searchservices",
    "microsoft.servicebus/namespaces": "microsoft.servicebus/namespaces",
    "microsoft.signalrservice/signalr": "microsoft.signalrservice/signalr",
    "microsoft.sql/locations": "microsoft.sql/locations",
    "microsoft.sql/longtermretentionservers": "microsoft.sql/longtermretentionservers",
    "microsoft.sql/managedinstances": "microsoft.sql/managedinstances",
    "microsoft.sql/servers": "microsoft.sql/servers",
    "microsoft.storage/storageaccounts": "microsoft.storage/storageaccounts",
    "microsoft.storagesync/storagesyncservices": "microsoft.storagesync/storagesyncservices",
    "microsoft.streamanalytics/streamingjobs": "microsoft.streamanalytics/streamingjobs",
    "microsoft.synapse/workspaces": "microsoft.synapse/workspaces",
    "microsoft.visualstudio/organizations": "microsoft.visualstudio/organizations",
    "microsoft.web/connections": "microsoft.web/connections",
    "microsoft.web/hostingenvironments": "microsoft.web/hostingenvironments",
    "microsoft.web/serverfarms": "microsoft.web/serverfarms",
    "microsoft.web/sites": "microsoft.web/sites"
}

METER_SUB_CATEGORY = {
    "AI": "AI",
    "Analytics Storage": "Analytics Storage",
    "Azure Arc": "Azure Arc",
    "Azure CDN from Microsoft": "Azure CDN from Microsoft",
    "Azure CDN from Verizon": "Azure CDN from Verizon",
    "Azure Databricks Regional": "Azure Databricks Regional",
    "Azure Data Lake Storage Gen2 Flat Namespace": "Azure Data Lake Storage Gen2 Flat Namespace",
    "Azure Data Lake Storage Gen2 Hierarchical Namespace": "Azure Data Lake Storage Gen2 Hierarchical Namespace",
    "Azure Front Door": "Azure Front Door",
    "Azure OpenAI": "Azure OpenAI",
    "Azure Pipelines": "Azure Pipelines",
    "Azure Purview Data Map": "Azure Purview Data Map",
    "Azure Purview Scanning Ingestion and Classification": "Azure Purview Scanning Ingestion and Classification",
    "Azure Repos and Boards (Basic)": "Azure Repos and Boards (Basic)",
    "Azure Synapse Analytics Storage": "Azure Synapse Analytics Storage",
    "Azure Synapse Link for SQL": "Azure Synapse Link for SQL",
    "Azure Test Plans": "Azure Test Plans",
    "Azure Virtual Network Manager": "Azure Virtual Network Manager",
    "B2X": "B2X",
    "Bandwidth": "Bandwidth",
    "Basic": "Basic",
    "Basic Plan": "Basic Plan",
    "Basic Plan - Linux": "Basic Plan - Linux",
    "Blob Features": "Blob Features",
    "BS Series": "BS Series",
    "BS Series Windows": "BS Series Windows",
    "Computer Vision": "Computer Vision",
    "Dadsv5 Series": "Dadsv5 Series",
    "Dadsv5 Series VM": "Dadsv5 Series VM",
    "Dasv5 Series": "Dasv5 Series",
    "Dasv5 Series VM": "Dasv5 Series VM",
    "Data Flow - Basic": "Data Flow - Basic",
    "Data Flow - General Purpose": "Data Flow - General Purpose",
    "Data Governance": "Data Governance",
    "Data Transfer": "Data Transfer",
    "Dav4/Dasv4 Series": "Dav4/Dasv4 Series",
    "Ddsv4 Series": "Ddsv4 Series",
    "Ddsv5 Series": "Ddsv5 Series",
    "Dedicated SQL Pool": "Dedicated SQL Pool",
    "Disaster Recovery Storage": "Disaster Recovery Storage",
    "Document Intelligence": "Document Intelligence",
    "Dplsv5 Series Linux": "Dplsv5 Series Linux",
    "Dplsv5 Series VM": "Dplsv5 Series VM",
    "Dpsv5 Series": "Dpsv5 Series",
    "Dpsv6 Series": "Dpsv6 Series",
    "Dpsv6 Series VM": "Dpsv6 Series VM",
    "DSv3 Series VM": "DSv3 Series VM",
    "Dsv5 Series": "Dsv5 Series",
    "Dv2/DSv2 Series": "Dv2/DSv2 Series",
    "Dv2/DSv2 Series Windows": "Dv2/DSv2 Series Windows",
    "Dv3/DSv3 Series": "Dv3/DSv3 Series",
    "Dv3/DSv3 Series Windows": "Dv3/DSv3 Series Windows",
    "Eadsv5 Series": "Eadsv5 Series",
    "Eadsv5 Series VM": "Eadsv5 Series VM",
    "Easv5 Series": "Easv5 Series",
    "Easv5 Series VM": "Easv5 Series VM",
    "Eav4/Easv4 Series": "Eav4/Easv4 Series",
    "Eav4/Easv4 Series Windows": "Eav4/Easv4 Series Windows",
    "Ebdsv5 Series Windows": "Ebdsv5 Series Windows",
    "Edsv4 Series": "Edsv4 Series",
    "Edsv4 Series VM": "Edsv4 Series VM",
    "Edv4 Series": "Edv4 Series",
    "Edv5 Series": "Edv5 Series",
    "Edv5 Series VM": "Edv5 Series VM",
    "Elastic Jobs Agent": "Elastic Jobs Agent",
    "Ev3/ESv3 Series": "Ev3/ESv3 Series",
    "Fabric Capacity": "Fabric Capacity",
    "F/FS Series": "F/FS Series",
    "Files": "Files",
    "Files v2": "Files v2",
    "File Sync": "File Sync",
    "Flexible Server Burstable BS Series Compute": "Flexible Server Burstable BS Series Compute",
    "Flexible Server Storage": "Flexible Server Storage",
    "Free Plan": "Free Plan",
    "Free Plan - Linux": "Free Plan - Linux",
    "General Block Blob": "General Block Blob",
    "General Block Blob v2 Hierarchical Namespace": "General Block Blob v2 Hierarchical Namespace",
    "General Purpose - Compute Gen5": "General Purpose - Compute Gen5",
    "General Purpose - Serverless - Compute Gen5": "General Purpose - Serverless - Compute Gen5",
    "General Purpose - Storage": "General Purpose - Storage",
    "Global Peering": "Global Peering",
    "Hyperscale - Serverless - Compute Gen5": "Hyperscale - Serverless - Compute Gen5",
    "Hyperscale - Storage": "Hyperscale - Storage",
    "Inter-Region": "Inter-Region",
    "IP Addresses": "IP Addresses",
    "Isolated Plan": "Isolated Plan",
    "Key Vault": "Key Vault",
    "Language": "Language",
    "LTR Backup Storage": "LTR Backup Storage",
    "Managed Instance General Purpose - Compute Gen5": "Managed Instance General Purpose - Compute Gen5",
    "Managed Instance General Purpose - Latest Gen Memory Optimized Compute": "Managed Instance General Purpose - Latest Gen Memory Optimized Compute",
    "Managed Instance General Purpose - SQL License": "Managed Instance General Purpose - SQL License",
    "Managed Instance General Purpose - Storage": "Managed Instance General Purpose - Storage",
    "NAT Gateway": "NAT Gateway",
    "NCSv3 Series": "NCSv3 Series",
    "NVadsA10v5 Series": "NVadsA10v5 Series",
    "OneLake": "OneLake",
    "Peering": "Peering",
    "Pipelines": "Pipelines",
    "PITR": "PITR",
    "Power Automate Atnd Run PAYG": "Power Automate Atnd Run PAYG",
    "Premium": "Premium",
    "Premium ADLS Gen2 Hierarchical Namespace": "Premium ADLS Gen2 Hierarchical Namespace",
    "Premium Block Blob v2 Hierarchical Namespace": "Premium Block Blob v2 Hierarchical Namespace",
    "Premium Plan": "Premium Plan",
    "Premium SSD Managed Disks": "Premium SSD Managed Disks",
    "Premium v2 Plan": "Premium v2 Plan",
    "Private Link": "Private Link",
    "Process": "Process",
    "Public IP Prefix": "Public IP Prefix",
    "Queues": "Queues",
    "Queues v2": "Queues v2",
    "Routing Preference: Internet": "Routing Preference: Internet",
    "Rtn Preference: MGN": "Rtn Preference: MGN",
    "Single Basic": "Single Basic",
    "SingleDB/Elastic Pool Hyperscale - Compute Gen5": "SingleDB/Elastic Pool Hyperscale - Compute Gen5",
    "SingleDB/Elastic Pool Hyperscale - SQL License": "SingleDB/Elastic Pool Hyperscale - SQL License",
    "SingleDB Hyperscale - Serverless - Read Repl - Compute Gen5": "SingleDB Hyperscale - Serverless - Read Repl - Compute Gen5",
    "SingleDB Hyperscale - Storage": "SingleDB Hyperscale - Storage",
    "Single/Elastic Pool General Purpose - Compute Gen5": "Single/Elastic Pool General Purpose - Compute Gen5",
    "Single/Elastic Pool General Purpose - SQL License": "Single/Elastic Pool General Purpose - SQL License",
    "Single/Elastic Pool General Purpose - Storage": "Single/Elastic Pool General Purpose - Storage",
    "Single/Elastic Pool PITR Backup Storage": "Single/Elastic Pool PITR Backup Storage",
    "Single Serverless Hyperscale General Purpose": "Single Serverless Hyperscale General Purpose",
    "Single Standard": "Single Standard",
    "Spark Pool - Memory Optimized": "Spark Pool - Memory Optimized",
    "Speech": "Speech",
    "SQL Database": "SQL Database",
    "SQL Server Developer Edition": "SQL Server Developer Edition",
    "SQL Server Express Edition": "SQL Server Express Edition",
    "SQL Serverless": "SQL Serverless",
    "Standard": "Standard",
    "Windows Server": "Windows Server"
}

RESOURCE_LOCATION_MAPPING = {
    "CA Central": "CA Central",
    "CA East": "CA East",
    "EU North": "EU North",
    "EU West": "EU West",
    "FR Central": "FR Central",
    "global": "global",
    "IN Central": "IN Central",
    "IT North": "IT North",
    "PL Central": "PL Central",
    "SE Central": "SE Central",
    "UK South": "UK South",
    "Unknown": "Unknown",
    "US Central": "US Central",
    "US East": "US East",
    "US East 2": "US East 2",
    "US North Central": "US North Central",
    "US West": "US West",
    "US West 2": "US West 2"
}

METER_CATEGORY_MAPPING = {
    "App Configuration": "App Configuration",
    "Application Gateway": "Application Gateway",
    "Automation": "Automation",
    "Azure Active Directory for External Identities": "Azure Active Directory for External Identities",
    "Azure Applied AI Services": "Azure Applied AI Services",
    "Azure App Service": "Azure App Service",
    "Azure Arc": "Azure Arc",
    "Azure Bastion": "Azure Bastion",
    "Azure Bot Service": "Azure Bot Service",
    "Azure Cognitive Search": "Azure Cognitive Search",
    "Azure Container Apps": "Azure Container Apps",
    "Azure Cosmos DB": "Azure Cosmos DB",
    "Azure Database for MySQL": "Azure Database for MySQL",
    "Azure Database for PostgreSQL": "Azure Database for PostgreSQL",
    "Azure Databricks": "Azure Databricks",
    "Azure Data Explorer": "Azure Data Explorer",
    "Azure Data Factory v2": "Azure Data Factory v2",
    "Azure DevOps": "Azure DevOps",
    "Azure DNS": "Azure DNS",
    "Azure Front Door Service": "Azure Front Door Service",
    "Azure Kubernetes Service": "Azure Kubernetes Service",
    "Azure Monitor": "Azure Monitor",
    "Azure Purview": "Azure Purview",
    "Azure Site Recovery": "Azure Site Recovery",
    "Azure Synapse Analytics": "Azure Synapse Analytics",
    "Backup": "Backup",
    "Bandwidth": "Bandwidth",
    "Cognitive Services": "Cognitive Services",
    "Container Instances": "Container Instances",
    "Container Registry": "Container Registry",
    "Content Delivery Network": "Content Delivery Network",
    "Data Lake Analytics": "Data Lake Analytics",
    "Data Lake Store": "Data Lake Store",
    "Dataverse": "Dataverse",
    "Event Grid": "Event Grid",
    "Event Hubs": "Event Hubs",
    "Functions": "Functions",
    "Key Vault": "Key Vault",
    "Load Balancer": "Load Balancer",
    "Log Analytics": "Log Analytics",
    "Logic Apps": "Logic Apps",
    "Microsoft Defender for Cloud": "Microsoft Defender for Cloud",
    "Microsoft Entra Domain Services": "Microsoft Entra Domain Services",
    "Microsoft Fabric": "Microsoft Fabric",
    "Microsoft Purview": "Microsoft Purview",
    "NAT Gateway": "NAT Gateway",
    "Network Watcher": "Network Watcher",
    "Power Automate": "Power Automate",
    "Power BI Embedded": "Power BI Embedded",
    "Redis Cache": "Redis Cache",
    "Sentinel": "Sentinel",
    "Service Bus": "Service Bus",
    "SignalR": "SignalR",
    "SQL Database": "SQL Database",
    "SQL Managed Instance": "SQL Managed Instance",
    "Storage": "Storage",
    "Stream Analytics": "Stream Analytics",
    "Traffic Manager": "Traffic Manager",
    "Unassigned": "Unassigned",
    "Virtual Machines": "Virtual Machines",
    "Virtual Machines Licenses": "Virtual Machines Licenses",
    "Virtual Network": "Virtual Network",
    "VPN Gateway": "VPN Gateway"
}

RN_ACCOUNT_MAPPING = {
    "colbette holdings ltd - cash 4 members": "colbette holdings ltd - cash 4 members",
    "colbette holdings ltd - mydirtyhobby": "colbette holdings ltd - mydirtyhobby",
    "colbette holdings ltd - mydirtyhobby storage": "colbette holdings ltd - mydirtyhobby storage",
    "colbette holdings ltd - privatamateure": "colbette holdings ltd - privatamateure",
    "mindgeek 3dxstar": "mindgeek 3dxstar",
    "mindgeek adtool": "mindgeek adtool",
    "mindgeek adtool 7": "mindgeek adtool 7",
    "mindgeek ageid": "mindgeek ageid",
    "mindgeek atlas support": "mindgeek atlas support",
    "mindgeek babes": "mindgeek babes",
    "mindgeek bes": "mindgeek bes",
    "mindgeek billing-risk": "mindgeek billing-risk",
    "mindgeek billing system": "mindgeek billing system",
    "mindgeek bonusvids": "mindgeek bonusvids",
    "mindgeek brazzers": "mindgeek brazzers",
    "mindgeek brightsector software": "mindgeek brightsector software",
    "mindgeek cdn": "mindgeek cdn",
    "mindgeek clog": "mindgeek clog",
    "mindgeek cose mtl": "mindgeek cose mtl",
    "mindgeek cpa sales": "mindgeek cpa sales",
    "mindgeek crm": "mindgeek crm",
    "mindgeek dark district": "mindgeek dark district",
    "mindgeek data science": "mindgeek data science",
    "mindgeek devops": "mindgeek devops",
    "mindgeek dmp": "mindgeek dmp",
    "mindgeek donormass": "mindgeek donormass",
    "mindgeek dp": "mindgeek dp",
    "mindgeek dws": "mindgeek dws",
    "mindgeek eng monitoring": "mindgeek eng monitoring",
    "mindgeek fapdu storage & cdn > sub account of c4101": "mindgeek fapdu storage & cdn > sub account of c4101",
    "mindgeek gaytube": "mindgeek gaytube",
    "mindgeek glorious holdings et": "mindgeek glorious holdings et",
    "mindgeek glorious holdings km": "mindgeek glorious holdings km",
    "mindgeek glorious holdings ms": "mindgeek glorious holdings ms",
    "mindgeek glorious holdings sw": "mindgeek glorious holdings sw",
    "mindgeek hubtraffic": "mindgeek hubtraffic",
    "mindgeek it": "mindgeek it",
    "mindgeek it systems": "mindgeek it systems",
    "mindgeek keycloak": "mindgeek keycloak",
    "mindgeek law enforcement compliance": "mindgeek law enforcement compliance",
    "mindgeek lb": "mindgeek lb",
    "mindgeek mainhub": "mindgeek mainhub",
    "mindgeek mesos": "mindgeek mesos",
    "mindgeek mobile": "mindgeek mobile",
    "mindgeek mobile apps": "mindgeek mobile apps",
    "mindgeek mofos": "mindgeek mofos",
    "mindgeek moviebox": "mindgeek moviebox",
    "mindgeek niche products": "mindgeek niche products",
    "mindgeek nutaku": "mindgeek nutaku",
    "mindgeek nutaku games": "mindgeek nutaku games",
    "mindgeek onema": "mindgeek onema",
    "mindgeek paysite product": "mindgeek paysite product",
    "mindgeek paysites box": "mindgeek paysites box",
    "mindgeek phsa": "mindgeek phsa",
    "mindgeek pornhub": "mindgeek pornhub",
    "mindgeek pornhub originals": "mindgeek pornhub originals",
    "mindgeek pornhub originals storage": "mindgeek pornhub originals storage",
    "mindgeek pornhub originals storage 2": "mindgeek pornhub originals storage 2",
    "mindgeek pornhub originals storage 3": "mindgeek pornhub originals storage 3",
    "mindgeek pornhub originals storage 4": "mindgeek pornhub originals storage 4",
    "mindgeek pornhub originals storage 5": "mindgeek pornhub originals storage 5",
    "mindgeek pornhub originals storage 6": "mindgeek pornhub originals storage 6",
    "mindgeek pornhub originals storage 7": "mindgeek pornhub originals storage 7",
    "mindgeek pornhub originals storage 8": "mindgeek pornhub originals storage 8",
    "mindgeek pornhub private data": "mindgeek pornhub private data",
    "mindgeek pornhub storage": "mindgeek pornhub storage",
    "mindgeek pornhub storage 2": "mindgeek pornhub storage 2",
    "mindgeek pornhub storage 3": "mindgeek pornhub storage 3",
    "mindgeek pornhub storage 4": "mindgeek pornhub storage 4",
    "mindgeek pornhub storage 5": "mindgeek pornhub storage 5",
    "mindgeek pornhub storage 6": "mindgeek pornhub storage 6",
    "mindgeek pornhub storage 7": "mindgeek pornhub storage 7",
    "mindgeek pornhub storage 8": "mindgeek pornhub storage 8",
    "mindgeek pornhub storage new codecs": "mindgeek pornhub storage new codecs",
    "mindgeek pornhub vp9": "mindgeek pornhub vp9",
    "mindgeek pornhub vp9 storage": "mindgeek pornhub vp9 storage",
    "mindgeek pornhub vp9 storage 2": "mindgeek pornhub vp9 storage 2",
    "mindgeek pornhub vp9 storage 3": "mindgeek pornhub vp9 storage 3",
    "mindgeek pornhub vp9 storage 4": "mindgeek pornhub vp9 storage 4",
    "mindgeek pornhub vp9 storage 5": "mindgeek pornhub vp9 storage 5",
    "mindgeek pornhub vp 9 storage 6": "mindgeek pornhub vp 9 storage 6",
    "mindgeek pornmd": "mindgeek pornmd",
    "mindgeek porn portal": "mindgeek porn portal",
    "mindgeek processing cluster": "mindgeek processing cluster",
    "mindgeek projectone content": "mindgeek projectone content",
    "mindgeek projectone gateway": "mindgeek projectone gateway",
    "mindgeek realitydudes": "mindgeek realitydudes",
    "mindgeek realitygang": "mindgeek realitygang",
    "mindgeek reallyusefulcash": "mindgeek reallyusefulcash",
    "mindgeek redtube": "mindgeek redtube",
    "mindgeek rk": "mindgeek rk",
    "mindgeek rk storage": "mindgeek rk storage",
    "mindgeek searchlight - dmca": "mindgeek searchlight - dmca",
    "mindgeek seo": "mindgeek seo",
    "mindgeek traffic junky": "mindgeek traffic junky",
    "mindgeek traffic junky ams origin": "mindgeek traffic junky ams origin",
    "mindgeek traffic junky storage": "mindgeek traffic junky storage",
    "mindgeek traffic junky storage 2": "mindgeek traffic junky storage 2",
    "mindgeek trust & safety": "mindgeek trust & safety",
    "mindgeek tube8": "mindgeek tube8",
    "mindgeek tubes backup": "mindgeek tubes backup",
    "mindgeek tubes services": "mindgeek tubes services",
    "mindgeek twistys": "mindgeek twistys",
    "mindgeek uploads temporary storage": "mindgeek uploads temporary storage",
    "mindgeek usp": "mindgeek usp",
    "mindgeek uviu": "mindgeek uviu",
    "mindgeek xtube": "mindgeek xtube",
    "mindgeek youporn": "mindgeek youporn"
}



PRODUCT_NAME = {
    "ded4411": "ded4411",
    "ded6201": "ded6201",
    "elasticsearch03.dd3": "elasticsearch03.dd3",
    "db05.mdh": "db05.mdh",
    "firefox08.processing": "firefox08.processing",
    "db03.pornhub.com": "db03.pornhub.com",
    "tjdelivery219.trafficjunky.net": "tjdelivery219.trafficjunky.net",
    "lb04.cdn.ams10": "lb04.cdn.ams10",
    "rnclog2-elasticsearch-05": "rnclog2-elasticsearch-05",
    "kafka00_stage.trafficjunky.net": "kafka00_stage.trafficjunky.net",
    "lightning23.ord.processing": "lightning23.ord.processing",
    "www02.uviu.com": "www02.uviu.com",
    "ded6067": "ded6067",
    "redis02.authent": "redis02.authent",
    "http01.mindgeek.par2": "http01.mindgeek.par2",
    "alohavirtlab04.int.haproxy.com": "alohavirtlab04.int.haproxy.com",
    "ded1604": "ded1604",
    "mgclog2-parser05": "mgclog2-parser05",
    "kafka01.ord.c3803": "kafka01.ord.c3803",
    "worker02.k8s.c5181.datascience.ams": "worker02.k8s.c5181.datascience.ams",
    "grafana.adtool": "grafana.adtool",
    "lb05.mindgeek.ams10": "lb05.mindgeek.ams10",
    "clickhouse-analytics-02": "clickhouse-analytics-02",
    "ded6774": "ded6774",
    "www01.moviebox": "www01.moviebox",
    "ded7145": "ded7145",
    "srv07.ph.bsector": "srv07.ph.bsector",
    "ded1639": "ded1639",
    "cassandra02.prod.ord.mgdmp": "cassandra02.prod.ord.mgdmp",
    "ded6261": "ded6261"
}
