# USAGE_FAM_MAPPING dictionary
USAGE_FAM_MAPPING = {
    "AWS Service Catalog": "AWSServiceCatalog",
    "Amazon Simple Queue Service": "AWSQueueService",
    "AWS Glue": "AWSGlue",
    "AWS Data Transfer": "AWSDataTransfer",
    "AWS Secrets Manager": "AWSSecretsManager",
    "AWS Key Management Service": "awskms",
    "Amazon Simple Notification Service": "AmazonSNS",
    "Amazon Simple Storage Service": "AmazonS3",
    "AmazonCloudWatch": "AmazonCloudWatch",
    "AWS Migration Hub Refactor Spaces": "AWSMigrationHubRefactorSpaces",
    "AWS Lambda": "AWSLambda",
    "Amazon Elastic Compute Cloud": "AmazonEC2",
    "AWS CloudTrail": "AWSCloudTrail",
    "Amazon DynamoDB": "AmazonDynamoDB",
    "Amazon Relational Database Service": "AmazonRDS",
    "Amazon API Gateway": "AmazonApiGateway",
    "Amazon Elastic Container Registry Public": "AmazonECRPublic",
    "Amazon EC2 Container Registry (ECR)": "AmazonECR",
    "Amazon Virtual Private Cloud": "AmazonVPC",
    "Amazon Elastic Container Service": "AmazonECS",
    "Elastic Load Balancing": "AWSELB",
    "Amazon S3 Glacier Deep Archive": "AmazonS3GlacierDeepArchive",
    "Amazon Elastic File System": "AmazonEFS",
    "Amazon Rekognition": "AmazonRekognition",
    "Amazon Simple Email Service": "AmazonSES",
    "Amazon ElastiCache": "AmazonElastiCache",
    "Amazon OpenSearch Service": "AmazonES",
    "AWS DataSync": "AWSDataSync",
    "Amazon CloudFront": "AmazonCloudFront",
    "AWS Cost Explorer": "AWSCostExplorer",
    "AWS X-Ray": "AWSXRay",
    "Amazon Route 53": "AmazonRoute53",
    "Amazon Kinesis": "AmazonKinesis",
    "Amazon Redshift": "AmazonRedshift",
    "AWS Config": "AWSConfig",
    "AWS Elemental MediaLive": "AWSElementalMediaLive",
    "AWS Transfer Family": "AWSTransfer",
    "CloudWatch Events": "AWSEvents",
    "Amazon SimpleDB": "AmazonSimpleDB",
    "Amazon Elastic Container Service for Kubernetes": "AmazonEKS",
    "Amazon Lightsail": "AmazonLightsail",
    "AWS Backup": "AWSBackup",
    "Amazon Cognito": "AmazonCognito",
    "AWS Systems Manager": "AWSSystemsManager",
    "Amazon Elastic Compute Cloud - Compute": "AmazonEC2",
    "Tax": "AWSBilling",
    "Meta Llama 2 Chat 70B (Amazon Bedrock Edition)": "AmazonBedrockLlama70B",
    "Amazon Glacier": "AmazonS3GlacierDeepArchive",
    "AWS CloudFormation": "AWSCloudFormation",
    "Amazon Location Service": "AmazonLocation",
    "Amazon Managed Service for Prometheus": "AWSPrometheus",
    "Amazon Registrar": "AmazonRegistrar",
    "AWS WAF": "AWSWAF",
    "AWS Step Functions": "AWSStepFunctions",
    "Amazon SageMaker": "AmazonSageMaker",
    "Amazon Simple Workflow Service": "AmazonSWF",
    "Amazon Bedrock": "AmazonBedrock",
    "Amazon Interactive Video Service": "AmazonIVS",
    "Amazon MQ": "AmazonMQ",
    "Amazon Elastic Load Balancing": "AWSELB",
    "AWS CloudShell": "AWSCloudShell",
}

GCP_USAGE_UNITS = ["GB", "vCPU-hours", "Requests", "Operations", "Seconds"]

GCP_REGIONS = {
    "US": ["us-east1", "us-west1"],
    "EU": ["europe-west1"],
    "ASIA": ["asia-east1"],
}

GCP_COUNTRIES = ["United States", "Canada", "Germany", "India", "Japan"]

GCP_SELLERS = ["Google", "Google Cloud Partner", "Reseller A", "Reseller B"]
